name: Mobile App Generation and Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
      MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Run Tests (Optional, you can skip this if no tests are set up)
    - name: Run Tests
      run: npm run test

    # Step 5: Build the application
    - name: Build application
      run: npm run build

    # Step 6: Generate mobile app
    - name: Generate Mobile App
      run: |
        node dist/path/to/mobile-app.service.js
        node dist/path/to/app-generation.service.js

    # Step 7: Deploy app (Optional, depending on how/where you want to deploy)
    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        scp -i private_key -r dist/* $USER@$HOST:/path/to/deployment
