name: Build APK and Notify User

on:
  workflow_dispatch:
    inputs:
      appName:
        description: 'App Name'
        required: true
      appDesignId:
        description: 'App Design ID'
        required: true
      userId:
        description: 'User ID'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Notify user via Mailgun
        run: |
          curl -s --user "api:${{ secrets.MAILGUN_API_KEY }}" \
          https://api.mailgun.net/v3/${{ secrets.MAILGUN_DOMAIN }}/messages \
          -F from="Your App <no-reply@yourdomain.com>" \
          -F to="${{ github.event.inputs.userId }}" \
          -F subject="Your APK is ready!" \
          -F text="Your APK for the app '${{ github.event.inputs.appName }}' has been built. You can download it from: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts"
